In [1]:
import pandas as pd

In [2]:
sdwis = pd.read_excel("../SDWA_PUB_WATER_SYSTEMS.xlsx")

In [3]:
sdwis.head()

,SUBMISSIONYEARQUARTER,PWSID,PWS_NAME,PRIMACY_AGENCY_CODE,EPA_REGION,SEASON_BEGIN_DATE,SEASON_END_DATE,PWS_ACTIVITY_CODE,PWS_DEACTIVATION_DATE,PWS_TYPE_CODE,...,LAST_REPORTED_DATE,STATE_CODE,SOURCE_WATER_PROTECTION_CODE,SOURCE_PROTECTION_BEGIN_DATE,OUTSTANDING_PERFORMER,OUTSTANDING_PERFORM_BEGIN_DATE,REDUCED_RTCR_MONITORING,REDUCED_MONITORING_BEGIN_DATE,REDUCED_MONITORING_END_DATE,SEASONAL_STARTUP_SYSTEM
0,2025Q2,WA5325264,HANNAH HEIGHTS #2 WATER USERS ASSN,WA,10,NaT,NaT,A,NaT,CWS,...,2025-06-27,WA,NaN,NaT,Y,2024-06-12,NaN,NaT,NaT,NaN
1,2025Q2,LA1119034,GIL-GAL WATER SYSTEM,LA,6,NaT,NaT,A,NaT,CWS,...,2025-06-18,LA,N,NaT,NaN,NaT,NaN,NaT,NaT,NaN
2,2025Q2,NC0120414,THE MOUNTAIN FOLK CENTER,NC,4,2025-01-01,2025-12-31,A,NaT,TNCWS,...,2025-06-26,NC,NaN,NaT,NaN,NaT,NaN,NaT,NaT,NaN
3,2025Q2,AZ0413182,THAI GARDENS,AZ,9,2025-01-01,2025-12-31,A,NaT,TNCWS,...,2025-06-30,AZ,N,NaT,NaN,NaT,NaN,NaT,NaT,NaN
4,2025Q2,LA1073003,BETTER WATERWORKS WATER SYSTEM,LA,6,NaT,NaT,A,NaT,CWS,...,2025-06-18,LA,N,NaT,NaN,NaT,NaN,NaT,NaT,NaN

In [4]:
sdwis.columns

Index(['SUBMISSIONYEARQUARTER', 'PWSID', 'PWS_NAME', 'PRIMACY_AGENCY_CODE',
       'EPA_REGION', 'SEASON_BEGIN_DATE', 'SEASON_END_DATE',
       'PWS_ACTIVITY_CODE', 'PWS_DEACTIVATION_DATE', 'PWS_TYPE_CODE',
       'DBPR_SCHEDULE_CAT_CODE', 'CDS_ID', 'GW_SW_CODE',
       'LT2_SCHEDULE_CAT_CODE', 'OWNER_TYPE_CODE', 'POPULATION_SERVED_COUNT',
       'POP_CAT_2_CODE', 'POP_CAT_3_CODE', 'POP_CAT_4_CODE', 'POP_CAT_5_CODE',
       'POP_CAT_11_CODE', 'PRIMACY_TYPE', 'PRIMARY_SOURCE_CODE',
       'IS_GRANT_ELIGIBLE_IND', 'IS_WHOLESALER_IND',
       'IS_SCHOOL_OR_DAYCARE_IND', 'SERVICE_CONNECTIONS_COUNT',
       'SUBMISSION_STATUS_CODE', 'ORG_NAME', 'ADMIN_NAME', 'EMAIL_ADDR',
       'PHONE_NUMBER', 'PHONE_EXT_NUMBER', 'FAX_NUMBER', 'ALT_PHONE_NUMBER',
       'ADDRESS_LINE1', 'ADDRESS_LINE2', 'CITY_NAME', 'ZIP_CODE',
       'COUNTRY_CODE', 'FIRST_REPORTED_DATE', 'LAST_REPORTED_DATE',
       'STATE_CODE', 'SOURCE_WATER_PROTECTION_CODE',
       'SOURCE_PROTECTION_BEGIN_DATE', 'OUTSTANDING_PERFORMER',
       'OUTSTANDING_PERFORM_BEGIN_DATE', 'REDUCED_RTCR_MONITORING',
       'REDUCED_MONITORING_BEGIN_DATE', 'REDUCED_MONITORING_END_DATE',
       'SEASONAL_STARTUP_SYSTEM'],
      dtype='object')

In [5]:
sdwis['PWS_ACTIVITY_CODE'].unique() # check the values in pws_activity_code column

array(['A', 'I', 'N', 'P', 'M'], dtype=object)

In [6]:
sdwis['PWS_ACTIVITY_CODE'].nunique()

5

In [7]:
sdwis['PWS_ACTIVITY_CODE'].describe()

count     432695
unique         5
top            I
freq      261815
Name: PWS_ACTIVITY_CODE, dtype: object

In [8]:
filter_sdwis = sdwis.query('PWS_ACTIVITY_CODE == "A"').copy() # filtered with ACTIVE PWSID

In [9]:
filter_sdwis["GW_SW_CODE"].describe()

count     143213
unique         2
top           GW
freq      128428
Name: GW_SW_CODE, dtype: object

In [10]:
filter_sdwis["GW_SW_CODE"].isna().sum()

np.int64(23)

In [11]:
missing_source = filter_sdwis.loc[filter_sdwis['GW_SW_CODE'].isna(), ['PWSID', 'GW_SW_CODE','PRIMARY_SOURCE_CODE']]

In [12]:
missing_source #PWSID WITH NO GW and SW Source

            PWSID GW_SW_CODE PRIMARY_SOURCE_CODE
19345   NY4930302        NaN                 NaN
41839   NY3530367        NaN                 NaN
51423   NY5030114        NaN                 NaN
54961   PR0303043        NaN                 NaN
67614   TX1013797        NaN                 NaN
92526   NY6100055        NaN                 NaN
93238   NY4998097        NaN                 NaN
94933   NY5630157        NaN                 NaN
97727   NH0757030        NaN                 NaN
103923  TX1050182        NaN                 NaN
114457  NY1330699        NaN                 NaN
131487  NY6130053        NaN                 NaN
413021  WA5311260        NaN                 NaN
413539  VI1000284        NaN                 NaN
414448  NY1500310        NaN                 NaN
414451  NY5630158        NaN                 NaN
414864  NY5730136        NaN                 NaN
414903  FL5364187        NaN                 NaN
418030  MA3330027        NaN                 NaN
418129  MD1061068        NaN                 NaN
418456  WA5375670        NaN                 NaN
418457  WA5382200        NaN                 NaN
418635  NY3781127        NaN                 NaN

In [13]:
filter_sdwis["PWS_TYPE_CODE"].unique()

array(['CWS', 'TNCWS', 'NTNCWS'], dtype=object)

In [14]:
filter_sdwis["PWS_TYPE_CODE"].describe()

count     143236
unique         3
top        TNCWS
freq       76732
Name: PWS_TYPE_CODE, dtype: object

In [15]:
filter_sdwis["PWS_TYPE_CODE"].value_counts()

PWS_TYPE_CODE
TNCWS     76732
CWS       49377
NTNCWS    17127
Name: count, dtype: int64

In [16]:
filter_sdwis = filter_sdwis.drop(index=missing_source.index) #dropped all the pwsid with missing source

In [17]:
filter_sdwis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 143213 entries, 0 to 431904
Data columns (total 51 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   SUBMISSIONYEARQUARTER           143213 non-null  object
 1   PWSID                           143213 non-null  object
 2   PWS_NAME                        143213 non-null  object
 3   PRIMACY_AGENCY_CODE             143213 non-null  object
 4   EPA_REGION                      143213 non-null  int64
 5   SEASON_BEGIN_DATE               93846 non-null   datetime64[ns]
 6   SEASON_END_DATE                 93846 non-null   datetime64[ns]
 7   PWS_ACTIVITY_CODE               143213 non-null  object
 8   PWS_DEACTIVATION_DATE           0 non-null       datetime64[ns]
 9   PWS_TYPE_CODE                   143213 non-null  object
 10  DBPR_SCHEDULE_CAT_CODE          33323 non-null   float64
 11  CDS_ID                          14620 non-null   object
 12  GW_SW_CODE                      143213 non-null  object
 13  LT2_SCHEDULE_CAT_CODE           2322 non-null    float64
 14  OWNER_TYPE_CODE                 143207 non-null  object
 15  POPULATION_SERVED_COUNT         143213 non-null  int64
 16  POP_CAT_2_CODE                  143213 non-null  int64
 17  POP_CAT_3_CODE                  143213 non-null  int64
 18  POP_CAT_4_CODE                  143213 non-null  int64
 19  POP_CAT_5_CODE                  143213 non-null  int64
 20  POP_CAT_11_CODE                 143213 non-null  int64
 21  PRIMACY_TYPE                    143213 non-null  object
 22  PRIMARY_SOURCE_CODE             143213 non-null  object
 23  IS_GRANT_ELIGIBLE_IND           143213 non-null  object
 24  IS_WHOLESALER_IND               143213 non-null  object
 25  IS_SCHOOL_OR_DAYCARE_IND        143213 non-null  object
 26  SERVICE_CONNECTIONS_COUNT       143212 non-null  float64
 27  SUBMISSION_STATUS_CODE          143213 non-null  object
 28  ORG_NAME                        142501 non-null  object
 29  ADMIN_NAME                      125117 non-null  object
 30  EMAIL_ADDR                      83182 non-null   object
 31  PHONE_NUMBER                    112653 non-null  object
 32  PHONE_EXT_NUMBER                6428 non-null    object
 33  FAX_NUMBER                      21942 non-null   object
 34  ALT_PHONE_NUMBER                814 non-null     float64
 35  ADDRESS_LINE1                   136905 non-null  object
 36  ADDRESS_LINE2                   31216 non-null   object
 37  CITY_NAME                       142695 non-null  object
 38  ZIP_CODE                        142677 non-null  object
 39  COUNTRY_CODE                    142719 non-null  object
 40  FIRST_REPORTED_DATE             143213 non-null  datetime64[ns]
 41  LAST_REPORTED_DATE              142972 non-null  datetime64[ns]
 42  STATE_CODE                      142694 non-null  object
 43  SOURCE_WATER_PROTECTION_CODE    68972 non-null   object
 44  SOURCE_PROTECTION_BEGIN_DATE    13023 non-null   datetime64[ns]
 45  OUTSTANDING_PERFORMER           9953 non-null    object
 46  OUTSTANDING_PERFORM_BEGIN_DATE  4142 non-null    datetime64[ns]
 47  REDUCED_RTCR_MONITORING         16301 non-null   object
 48  REDUCED_MONITORING_BEGIN_DATE   16296 non-null   datetime64[ns]
 49  REDUCED_MONITORING_END_DATE     493 non-null     datetime64[ns]
 50  SEASONAL_STARTUP_SYSTEM         13043 non-null   object
dtypes: datetime64[ns](9), float64(4), int64(7), object(31)
memory usage: 56.8+ MB

In [18]:
filter_sdwis.isna().sum()

SUBMISSIONYEARQUARTER                  0
PWSID                                  0
PWS_NAME                               0
PRIMACY_AGENCY_CODE                    0
EPA_REGION                             0
SEASON_BEGIN_DATE                  49367
SEASON_END_DATE                    49367
PWS_ACTIVITY_CODE                      0
PWS_DEACTIVATION_DATE             143213
PWS_TYPE_CODE                          0
DBPR_SCHEDULE_CAT_CODE            109890
CDS_ID                            128593
GW_SW_CODE                             0
LT2_SCHEDULE_CAT_CODE             140891
OWNER_TYPE_CODE                        6
POPULATION_SERVED_COUNT                0
POP_CAT_2_CODE                         0
POP_CAT_3_CODE                         0
POP_CAT_4_CODE                         0
POP_CAT_5_CODE                         0
POP_CAT_11_CODE                        0
PRIMACY_TYPE                           0
PRIMARY_SOURCE_CODE                    0
IS_GRANT_ELIGIBLE_IND                  0
IS_WHOLESALER_IND                      0
IS_SCHOOL_OR_DAYCARE_IND               0
SERVICE_CONNECTIONS_COUNT              1
SUBMISSION_STATUS_CODE                 0
ORG_NAME                             712
ADMIN_NAME                         18096
EMAIL_ADDR                         60031
PHONE_NUMBER                       30560
PHONE_EXT_NUMBER                  136785
FAX_NUMBER                        121271
ALT_PHONE_NUMBER                  142399
ADDRESS_LINE1                       6308
ADDRESS_LINE2                     111997
CITY_NAME                            518
ZIP_CODE                             536
COUNTRY_CODE                         494
FIRST_REPORTED_DATE                    0
LAST_REPORTED_DATE                   241
STATE_CODE                           519
SOURCE_WATER_PROTECTION_CODE       74241
SOURCE_PROTECTION_BEGIN_DATE      130190
OUTSTANDING_PERFORMER             133260
OUTSTANDING_PERFORM_BEGIN_DATE    139071
REDUCED_RTCR_MONITORING           126912
REDUCED_MONITORING_BEGIN_DATE     126917
REDUCED_MONITORING_END_DATE       142720
SEASONAL_STARTUP_SYSTEM           130170
dtype: int64

In [19]:
active_sdwis = filter_sdwis.query("PWS_TYPE_CODE == 'CWS'")[['PWSID','POPULATION_SERVED_COUNT']].copy() #filtered pws_type_code = cws

In [20]:
active_sdwis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49369 entries, 0 to 431904
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PWSID                    49369 non-null  object
 1   POPULATION_SERVED_COUNT  49369 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.1+ MB

In [21]:
def assign_pop_bin(pop):
    if pop <= 100:
        return '25 - 100'
    elif pop <= 500:
        return '101 - 500'
    elif pop <= 1000:
        return '501 - 1,000'
    elif pop <= 3300:
        return '1,001 - 3,300'
    elif pop <= 10000:
        return '3,301 - 10,000'
    elif pop <= 50000:
        return '10,001 - 50,000'
    elif pop <= 100000:
        return '50,001 - 100,000'
    elif pop <= 1000000:
        return '100,001 - 1,000,000'
    else:
        return '> 1,000,000'

In [22]:
active_sdwis['Population_bin'] = active_sdwis['POPULATION_SERVED_COUNT'].apply(assign_pop_bin)

In [23]:
active_sdwis.head() #active, with valid GW or SW source and with PWS_TYPE_CODE = CWS PWSID with Pop serve count and pop_bin

        PWSID  POPULATION_SERVED_COUNT  Population_bin
0   WA5325264                       44        25 - 100
1   LA1119034                     1551   1,001 - 3,300
4   LA1073003                     2160   1,001 - 3,300
9   KS2000306                     2093   1,001 - 3,300
18  TN0000746                     4171  3,301 - 10,000

In [24]:
active_sdwis["Population_bin"].value_counts() # Number of systems in each population bin (from SDWIS)

Population_bin
101 - 500              15098
25 - 100               11385
1,001 - 3,300           7972
501 - 1,000             5336
3,301 - 10,000          5000
10,001 - 50,000         3513
50,001 - 100,000         583
100,001 - 1,000,000      455
> 1,000,000               27
Name: count, dtype: int64

In [25]:
# Total count of active Community Water Systems in the US, aligned to population bins for scaling 
bin_order = [
    '25 - 100', '101 - 500', '501 - 1,000', '1,001 - 3,300', 
    '3,301 - 10,000', '10,001 - 50,000', '50,001 - 100,000', 
    '100,001 - 1,000,000', '> 1,000,000'
]

national_pws_vector = active_sdwis['Population_bin'].value_counts().reindex(bin_order)

national_pws_vector

Population_bin
25 - 100               11385
101 - 500              15098
501 - 1,000             5336
1,001 - 3,300           7972
3,301 - 10,000          5000
10,001 - 50,000         3513
50,001 - 100,000         583
100,001 - 1,000,000      455
> 1,000,000               27
Name: count, dtype: int64

In [26]:
national_universe = pd.DataFrame(national_pws_vector)

In [27]:
national_universe

                     count
Population_bin
25 - 100             11385
101 - 500            15098
501 - 1,000           5336
1,001 - 3,300         7972
3,301 - 10,000        5000
10,001 - 50,000       3513
50,001 - 100,000       583
100,001 - 1,000,000    455
> 1,000,000             27

In [28]:
national_universe = national_universe.rename(columns={'count': 'National_Systems'})
national_universe = national_universe.reset_index()

In [29]:
national_universe

        Population_bin  National_Systems
0             25 - 100             11385
1            101 - 500             15098
2          501 - 1,000              5336
3        1,001 - 3,300              7972
4       3,301 - 10,000              5000
5      10,001 - 50,000              3513
6     50,001 - 100,000               583
7  100,001 - 1,000,000               455
8          > 1,000,000                27

Established the National Universe by pulling the total count of all active Community Water Systems from the SDWIS database and organizing them into specific population bins.

In [30]:
ep_table = pd.read_csv('ep_table.csv')

In [31]:
ep_table.head()

,PWSID,FacilityID,PFOA,PFOS,exceeds,POPULATION_SERVED_COUNT,Ep_Population,Population_bin
0,AK2110342,29349,0.0,0.0,False,38526.0,19263.0,"10,001 - 50,000"
1,AK2110342,29360,0.0,0.0,False,38526.0,19263.0,"10,001 - 50,000"
2,AK2110601,10001,0.0,0.0,False,10947.0,5473.5,"3,301 - 10,000"
3,AK2110601,10004,0.0,0.0,False,10947.0,5473.5,"3,301 - 10,000"
4,AK2120232,TP001,0.0,0.0,False,8937.0,8937.0,"3,301 - 10,000"

In [32]:
ep_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26148 entries, 0 to 26147
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PWSID                    26148 non-null  object
 1   FacilityID               26148 non-null  object
 2   PFOA                     26148 non-null  float64
 3   PFOS                     26148 non-null  float64
 4   exceeds                  26148 non-null  bool
 5   POPULATION_SERVED_COUNT  26148 non-null  float64
 6   Ep_Population            26148 non-null  float64
 7   Population_bin           26148 non-null  object
dtypes: bool(1), float64(4), object(3)
memory usage: 1.4+ MB

In [33]:
ep_table['Ep_Population'] = ep_table['Ep_Population'].round()

In [34]:
ep_table.head()

,PWSID,FacilityID,PFOA,PFOS,exceeds,POPULATION_SERVED_COUNT,Ep_Population,Population_bin
0,AK2110342,29349,0.0,0.0,False,38526.0,19263.0,"10,001 - 50,000"
1,AK2110342,29360,0.0,0.0,False,38526.0,19263.0,"10,001 - 50,000"
2,AK2110601,10001,0.0,0.0,False,10947.0,5474.0,"3,301 - 10,000"
3,AK2110601,10004,0.0,0.0,False,10947.0,5474.0,"3,301 - 10,000"
4,AK2120232,TP001,0.0,0.0,False,8937.0,8937.0,"3,301 - 10,000"

In [35]:
# Count of all unique Entry Points (EPs) by Population Bin. Basically, a total sample size to calculate the risk of contamination
total_eps_per_bin = ep_table.groupby('Population_bin')['FacilityID'].nunique()
total_eps_per_bin

Population_bin
1,001 - 3,300          3512
10,001 - 50,000        2104
100,001 - 1,000,000     198
101 - 500               388
25 - 100                 69
3,301 - 10,000         3759
50,001 - 100,000        382
501 - 1,000             877
> 1,000,000               6
Name: FacilityID, dtype: int64

In [36]:
ep_table['Total_PFAS'] =  ep_table['PFOA'] + ep_table['PFOS']

In [37]:
thresholds = [4, 8, 12, 20, 40]

In [38]:
impacted_df = pd.DataFrame({'Population_bin': bin_order})

In [39]:
# for each regulatory threshold:
# Numerator: unique Eps that exceed the threshold
# Denominator: All unique EPs in that Population bin (total_eps_per_bin)
# Result: The Percent of impact for each bin 
for t in thresholds:
    threshold_ug = t / 1000
    
    # Matching  Cost Notebook 'OR' logic
    exceeding = (ep_table['PFOA'] > threshold_ug) | (ep_table['PFOS'] > threshold_ug)
    
    impacted_counts = ep_table[exceeding].groupby('Population_bin')['FacilityID'].nunique().reindex(bin_order)
    
    impacted_df[f'impacted_percent_{t}ng'] = (impacted_counts.values / total_eps_per_bin.reindex(bin_order).values).round(4) * 100
    
impacted_df = impacted_df.fillna(0)
impacted_df

,Population_bin,impacted_percent_4ng,impacted_percent_8ng,impacted_percent_12ng,impacted_percent_20ng,impacted_percent_40ng
0,25 - 100,10.14,2.90,1.45,1.45,1.45
1,101 - 500,5.93,2.06,1.03,0.26,0.26
2,"501 - 1,000",12.54,6.39,4.33,1.82,0.34
3,"1,001 - 3,300",10.59,5.81,3.25,1.51,0.46
4,"3,301 - 10,000",12.29,5.80,2.95,1.20,0.21
5,"10,001 - 50,000",11.98,5.70,3.37,1.62,0.29
6,"50,001 - 100,000",9.16,4.19,2.62,0.79,0.26
7,"100,001 - 1,000,000",16.16,6.06,5.56,1.52,0.00
8,"> 1,000,000",0.00,0.00,0.00,0.00,0.00

Developed the Impacted Dataframe using the UCMR5 sample data, where we calculated the specific percentage of unique entry points that exceeded each regulatory threshold based on a logical "OR" comparison of PFOA and PFOS levels

In [40]:
unique_eps = ep_table.drop_duplicates(subset=['PWSID', 'FacilityID'])

total_eps = len(unique_eps)
total_pws = ep_table['PWSID'].nunique()

M = total_eps / total_pws

print(f"Total Unique EPs: {total_eps}")
print(f"Total Unique PWS: {total_pws}")
print(f"National Multiplier: {M:.4f}")

Total Unique EPs: 26148
Total Unique PWS: 10155
National Multiplier: 2.5749

Calculated a National Multiplier representing the average number of entry points per water system.

In [41]:
final_national_impact = pd.DataFrame({'Population_bin': bin_order})
final_national_impact['National_PWS_Count'] = national_universe['National_Systems'].values

for t in thresholds:
    p_col = f'impacted_percent_{t}ng'
    
    # Formula: N (National Systems) * M (EPs per System) * P (Percent Impacted / 100)
    # We divide by 100 because the table currently has values like 11.98 instead of 0.1198
    final_national_impact[f'Estimated_EPs_to_Treat_{t}ng'] = (
        final_national_impact['National_PWS_Count'] * M * (impacted_df[p_col] / 100)
    ).round(0)

final_national_impact

,Population_bin,National_PWS_Count,Estimated_EPs_to_Treat_4ng,Estimated_EPs_to_Treat_8ng,Estimated_EPs_to_Treat_12ng,Estimated_EPs_to_Treat_20ng,Estimated_EPs_to_Treat_40ng
0,25 - 100,11385,2973.0,850.0,425.0,425.0,425.0
1,101 - 500,15098,2305.0,801.0,400.0,101.0,101.0
2,"501 - 1,000",5336,1723.0,878.0,595.0,250.0,47.0
3,"1,001 - 3,300",7972,2174.0,1193.0,667.0,310.0,94.0
4,"3,301 - 10,000",5000,1582.0,747.0,380.0,154.0,27.0
5,"10,001 - 50,000",3513,1084.0,516.0,305.0,147.0,26.0
6,"50,001 - 100,000",583,138.0,63.0,39.0,12.0,4.0
7,"100,001 - 1,000,000",455,189.0,71.0,65.0,18.0,0.0
8,"> 1,000,000",27,0.0,0.0,0.0,0.0,0.0

Finally, generated the Final Scaling Table by multiplying the national system counts by this multiplier and the bin-specific impact percentages